[package]
name = "simplex-subdivision-integration"
version = "0.1.0"
edition = "2021"

[dependencies]
num-dual = "0.6.0"
indextree = "4.6.0"
ndarray = "0.15.6"
linfa-linalg = "0.1.0"
#plotters = "0.3.4"
